name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: portfolio_grade
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/portfolio_grade?schema=public

      - name: Seed database
        run: npm run prisma:seed
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/portfolio_grade?schema=public

      - name: Build shared package
        run: npx nx build shared --skip-nx-cache
        env:
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Build API
        run: npx nx build api --skip-nx-cache
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/portfolio_grade?schema=public
          REDIS_URL: redis://localhost:6379
          JWT_ACCESS_SECRET: test_access_secret
          JWT_REFRESH_SECRET: test_refresh_secret
          JWT_ACCESS_TTL: 900s
          JWT_REFRESH_TTL: 7d
          TENANT_HEADER: X-Org-Id
          NODE_ENV: test
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Build Admin
        run: npx nx build admin --skip-nx-cache
        env:
          VITE_API_URL: http://localhost:3000/api
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Build Portal
        run: npx nx build portal --skip-nx-cache
        env:
          VITE_API_URL: http://localhost:3000/api
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Start API server
        run: |
          npx nx serve api --port=3000 &
          sleep 10
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/portfolio_grade?schema=public
          REDIS_URL: redis://localhost:6379
          JWT_ACCESS_SECRET: test_access_secret
          JWT_REFRESH_SECRET: test_refresh_secret
          JWT_ACCESS_TTL: 900s
          JWT_REFRESH_TTL: 7d
          TENANT_HEADER: X-Org-Id
          NODE_ENV: test
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Start Admin server
        run: |
          npx nx serve admin --port=4200 &
          sleep 10
        env:
          VITE_API_URL: http://localhost:3000/api
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Start Portal server
        run: |
          npx nx serve portal --port=4201 &
          sleep 10
        env:
          VITE_API_URL: http://localhost:3000/api
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false

      - name: Wait for services to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3000/api/health; do sleep 2; done'
          timeout 60 bash -c 'until curl -f http://localhost:4200; do sleep 2; done'
          timeout 60 bash -c 'until curl -f http://localhost:4201; do sleep 2; done'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Admin E2E tests
        run: npx playwright test --config=apps/admin-e2e/playwright.config.ts --project=chromium
        env:
          VITE_API_URL: http://localhost:3000/api

      - name: Run Portal E2E tests
        run: npx playwright test --config=apps/portal-e2e/playwright.config.ts --project=chromium
        env:
          VITE_API_URL: http://localhost:3000/api

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
