name: Unit Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: |
          npx nx run-many --target=test --all --skip-nx-cache --nx-cloud=false
        env:
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false
          NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 0

      - name: Generate test coverage report
        run: |
          npx nx run-many --target=test --all --coverage --skip-nx-cache --nx-cloud=false
        env:
          NX_DAEMON: false
          NX_CLOUD_DISTRIBUTED_EXECUTION: false
          NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 0

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/
          retention-days: 30
